global using Kitchen.Api.Tools;
global using Kitchen.Dal.Data;
global using Microsoft.EntityFrameworkCore;
global using Kitchen.Core.Interfaces;
global using Kitchen.Entities;
global using Kitchen.Api.Contracts.Responses;
global using Kitchen.Core.Services;
global using Kitchen.Dal.Interfaces;
global using Kitchen.Dal.Repositories;
