global using Kitchen.Api.Tools;
global using Kitchen.Dal.Data;
global using Microsoft.EntityFrameworkCore;
global using Kitchen.Entities.Entities;
global using Kitchen.Entities.Contracts;
global using Kitchen.Entities.Models;
global using Kitchen.Dal.Interfaces;
global using Kitchen.Dal.Repositories;
global using Microsoft.AspNetCore.Authorization;
