// <auto-generated />
using System;
using Kitchen.Dal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kitchen.Dal.Migrations
{
    [DbContext(typeof(KitchenContext))]
    [Migration("20230713071243_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kitchen.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2089),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2090),
                            Name = "Eggs",
                            UniqueId = new Guid("13f30ead-9983-4ae7-b46f-a2a96f6b2556")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2092),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2093),
                            Name = "Bacon",
                            UniqueId = new Guid("1b9b9c61-dbda-4fd1-9138-04b9cc749097")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2094),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2095),
                            Name = "Bread",
                            UniqueId = new Guid("9a8e3b60-c798-435e-ba14-4397534e9512")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2096),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2097),
                            Name = "Spaghettis",
                            UniqueId = new Guid("c17b4c5a-3c45-45dc-beb2-f19cd9d32fd0")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2100),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2100),
                            Name = "Guanciale",
                            UniqueId = new Guid("6aefa57f-5290-45d9-b32f-53e4487529a0")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2102),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2102),
                            Name = "Pecorino romano",
                            UniqueId = new Guid("bb7c38ef-d6ea-4977-b8e2-414b3f5e67f3")
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2104),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2104),
                            Name = "Tomatoes",
                            UniqueId = new Guid("bb079408-06b9-48e4-a8fe-0676b61c13ee")
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2105),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2106),
                            Name = "Beef",
                            UniqueId = new Guid("3e90c13b-98ef-4763-ac4e-9149ebfc0f7f")
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2108),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2109),
                            Name = "Pasta",
                            UniqueId = new Guid("712c37b7-73fe-466d-9d1f-12d47ba9f660")
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.PreparationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("PreparationStep");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2206),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2206),
                            RecipeId = 1,
                            Step = "Cook the eggs",
                            StepNumber = 1,
                            Title = "Cook eggs",
                            UniqueId = new Guid("30e7c5fc-8b7f-4500-8a27-839dd477d187")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2210),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2211),
                            RecipeId = 1,
                            Step = "Cook the bacon",
                            StepNumber = 2,
                            Title = "Cook bacon",
                            UniqueId = new Guid("0433efd9-b871-4ea4-bebb-8b81f1720de6")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2213),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2213),
                            RecipeId = 1,
                            Step = "Fry the bread",
                            StepNumber = 3,
                            Title = "Fry bread",
                            UniqueId = new Guid("ecb1a991-5d5a-4ceb-8a60-66b57b92069e")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2215),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2215),
                            RecipeId = 2,
                            Step = "Cook the guanciale",
                            StepNumber = 1,
                            Title = "Cook guanciale",
                            UniqueId = new Guid("ea6ac218-749f-40dc-a8ec-efc570d72402")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2217),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2217),
                            RecipeId = 2,
                            Step = "Cook the spaghetti",
                            StepNumber = 2,
                            Title = "Cook spaghetti",
                            UniqueId = new Guid("0384cc8a-5647-4f6e-a90e-d895559a1f82")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2220),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2220),
                            RecipeId = 3,
                            Step = "Fry the bacon",
                            StepNumber = 1,
                            Title = "Fry bacon",
                            UniqueId = new Guid("04887de2-e6ba-4d1b-acbd-d574a02b77e0")
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2222),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2222),
                            RecipeId = 3,
                            Step = "Cook the eggs",
                            StepNumber = 2,
                            Title = "Cook eggs",
                            UniqueId = new Guid("5b831497-e1aa-4060-aeb7-aa3046130a37")
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2224),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2224),
                            RecipeId = 4,
                            Step = "Cook the beef and the bacon",
                            StepNumber = 1,
                            Title = "Cook beef and bacon",
                            UniqueId = new Guid("b2f429df-fabd-4d61-8362-465c90ed1442")
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2226),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2226),
                            RecipeId = 4,
                            Step = "Cook the spaghetti",
                            StepNumber = 2,
                            Title = "Cook spaghetti",
                            UniqueId = new Guid("d667a68a-c7e3-4c34-aaca-61df92d5e1a5")
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2229),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2229),
                            RecipeId = 5,
                            Step = "Prepare the bolognese",
                            StepNumber = 1,
                            Title = "Prepare bolognese",
                            UniqueId = new Guid("0f0cf7ff-c321-45fe-8405-78f504e9ac1a")
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2231),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2232),
                            RecipeId = 5,
                            Step = "Prepare the bechamel",
                            StepNumber = 2,
                            Title = "Prepare bechamel",
                            UniqueId = new Guid("9ce7ca05-7561-4236-8e61-2a25a5866b77")
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2233),
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2234),
                            RecipeId = 5,
                            Step = "Prepare the lasagna and place it in the oven.",
                            StepNumber = 3,
                            Title = "Prepare lasagna",
                            UniqueId = new Guid("c6f50e96-5970-4f2f-974e-ef0769fbc072")
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCategoryId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1975),
                            Description = "Sometimes also called a 'fry-up', the full English breakfast consists of fried eggs, sausages, back bacon, tomatoes, mushrooms, fried bread and often a slice of white or black pudding (similar to bloodwurst). It is accompanied by tea or coffee and hot, buttered toast.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1976),
                            RecipeCategoryId = 1,
                            Title = "English breakfast",
                            UniqueId = new Guid("d9cac577-8b15-4628-b53d-f118ca8c39d4")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1986),
                            Description = "Spaghetti alla carbonara is an Italian pasta dish made with eggs, pecorino romano, guanciale and black pepper.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1986),
                            RecipeCategoryId = 2,
                            Title = "Spaghetti carbonara",
                            UniqueId = new Guid("ab65e457-9701-416d-a9b5-de9f88d53518")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2007),
                            Description = "A club sandwich, also called a clubhouse sandwich, is a sandwich consisting of bread (traditionally toasted), sliced cooked poultry, fried bacon, lettuce, tomato, and mayonnaise. It is often cut into quarters or halves and held together by cocktail sticks.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2007),
                            RecipeCategoryId = 2,
                            Title = "Club sandwich",
                            UniqueId = new Guid("e18e8bd4-5a9f-4f8f-9d25-0f20989f3550")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2010),
                            Description = "Spaghetti bolognese consists of spaghetti (long strings of pasta) with an Italian ragù (meat sauce) made with minced beef, bacon and tomatoes, served with Parmesan cheese. Spaghetti bolognese is one of the most popular pasta dishes eaten outside of Italy.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2010),
                            RecipeCategoryId = 3,
                            Title = "Spaghetti bolognese",
                            UniqueId = new Guid("2ab57e69-8dd1-4942-88e2-e39eace98291")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2012),
                            Description = "Lasagna Bolognese includes only fresh egg pasta, Bolognese ragù (slow-cooked meat sauce), creamy béchamel (white sauce) and plenty of grated Parmigiano cheese. The result is a melt in your mouth, creamy, decadent, and satisfying lasagna that is distinct to Italy.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2012),
                            RecipeCategoryId = 3,
                            Title = "Lasagna bolognese",
                            UniqueId = new Guid("354ec2fd-ad0a-4a32-b22a-4eadb615cb08")
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1898),
                            Description = "Breakfast is the first meal of the day usually eaten in the morning. The word in English refers to breaking the fasting period of the previous night.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1898),
                            Title = "Breakfast",
                            UniqueId = new Guid("1e14cf45-28cc-495a-ae52-f1e381d00213")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1901),
                            Description = "Lunch is a meal eaten around the middle of the day. It is commonly the second meal of the day, after breakfast, and varies in size by culture and region.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1901),
                            Title = "Lunch",
                            UniqueId = new Guid("33d97ac3-5d1e-4d7b-88c0-c5f0711d3a28")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1903),
                            Description = "Dinner usually refers to what is in many Western cultures the largest and most formal meal of the day.Historically, the largest meal used to be eaten around midday, and called dinner.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(1904),
                            Title = "Dinner",
                            UniqueId = new Guid("bd2e03b5-8252-4d52-91b2-5a93da6c6009")
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IngredientQuantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            RecipeId = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2146),
                            IngredientQuantity = "2 whole",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2146),
                            UniqueId = new Guid("b24efbe5-9083-40bc-9d3d-dd673186b018")
                        },
                        new
                        {
                            IngredientId = 2,
                            RecipeId = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2149),
                            IngredientQuantity = "100 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2149),
                            UniqueId = new Guid("52dee08d-31c3-44b8-8507-4430994b09f4")
                        },
                        new
                        {
                            IngredientId = 3,
                            RecipeId = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2151),
                            IngredientQuantity = "2 slices",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2152),
                            UniqueId = new Guid("5ccc05a9-c666-4c5e-a2b8-9c9bbe9a198d")
                        },
                        new
                        {
                            IngredientId = 7,
                            RecipeId = 1,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2155),
                            IngredientQuantity = "1 whole",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2155),
                            UniqueId = new Guid("708506f3-fe41-47fe-b734-f1557b0eb293")
                        },
                        new
                        {
                            IngredientId = 1,
                            RecipeId = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2157),
                            IngredientQuantity = "1 whole",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2157),
                            UniqueId = new Guid("c4372fa2-72f0-49d9-908d-8bf265719dbd")
                        },
                        new
                        {
                            IngredientId = 4,
                            RecipeId = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2159),
                            IngredientQuantity = "500 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2160),
                            UniqueId = new Guid("d4770a22-9656-4b31-a852-6d92ea4af9d9")
                        },
                        new
                        {
                            IngredientId = 5,
                            RecipeId = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2161),
                            IngredientQuantity = "200 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2162),
                            UniqueId = new Guid("6301b8fb-ec88-4f90-a76e-b4976ecb16ff")
                        },
                        new
                        {
                            IngredientId = 6,
                            RecipeId = 2,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2164),
                            IngredientQuantity = "50 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2165),
                            UniqueId = new Guid("70914b24-4c21-4dc9-91a8-5a1a2df583ea")
                        },
                        new
                        {
                            IngredientId = 2,
                            RecipeId = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2166),
                            IngredientQuantity = "75 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2166),
                            UniqueId = new Guid("ca54a8b6-15c6-4105-afc7-9f9cfabfdfd2")
                        },
                        new
                        {
                            IngredientId = 3,
                            RecipeId = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2168),
                            IngredientQuantity = "4 slices",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2168),
                            UniqueId = new Guid("fdf7faa5-e713-4329-bac3-a6394d348bb0")
                        },
                        new
                        {
                            IngredientId = 7,
                            RecipeId = 3,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2170),
                            IngredientQuantity = "1 whole",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2170),
                            UniqueId = new Guid("22e4ab15-f8ad-41b7-8687-4a96f8c87165")
                        },
                        new
                        {
                            IngredientId = 4,
                            RecipeId = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2173),
                            IngredientQuantity = "500 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2173),
                            UniqueId = new Guid("66588dc3-33ef-44c4-b304-8b9ad7a422f8")
                        },
                        new
                        {
                            IngredientId = 2,
                            RecipeId = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2175),
                            IngredientQuantity = "100 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2175),
                            UniqueId = new Guid("b1ac180c-ef44-424f-9dac-864951ee378d")
                        },
                        new
                        {
                            IngredientId = 7,
                            RecipeId = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2177),
                            IngredientQuantity = "3 tins of crushed tomatoes",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2177),
                            UniqueId = new Guid("1654a6a2-83b1-4517-b81e-fce4fdcf9c89")
                        },
                        new
                        {
                            IngredientId = 8,
                            RecipeId = 4,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2178),
                            IngredientQuantity = "250 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2179),
                            UniqueId = new Guid("bea1f458-1f05-4e28-b1e7-5b06125646cb")
                        },
                        new
                        {
                            IngredientId = 7,
                            RecipeId = 5,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2182),
                            IngredientQuantity = "2 tins of crushed tomatoes",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2182),
                            UniqueId = new Guid("a8de560d-36a3-489d-8611-de2a8edb0b77")
                        },
                        new
                        {
                            IngredientId = 8,
                            RecipeId = 5,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2184),
                            IngredientQuantity = "300 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2184),
                            UniqueId = new Guid("a991855a-1b29-4301-a19d-d4bdb318e479")
                        },
                        new
                        {
                            IngredientId = 9,
                            RecipeId = 5,
                            CreatedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2186),
                            IngredientQuantity = "250 g.",
                            ModifiedOn = new DateTime(2023, 7, 13, 7, 12, 43, 863, DateTimeKind.Utc).AddTicks(2186),
                            UniqueId = new Guid("5ba2a43a-605d-42f0-9a21-02a573bc5f8b")
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.PreparationStep", b =>
                {
                    b.HasOne("Kitchen.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Kitchen.Entities.Recipe", b =>
                {
                    b.HasOne("Kitchen.Entities.RecipeCategory", "RecipeCategory")
                        .WithMany()
                        .HasForeignKey("RecipeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeCategory");
                });

            modelBuilder.Entity("Kitchen.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Kitchen.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kitchen.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Kitchen.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Kitchen.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
