// <auto-generated />
using System;
using Kitchen.Dal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kitchen.Dal.Migrations
{
    [DbContext(typeof(KitchenContext))]
    [Migration("20230226152831_CreatedOnAdded")]
    partial class CreatedOnAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kitchen.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0001-0000-000000000000"),
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0002-0000-000000000000"),
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0000-000000000000"),
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0004-0000-000000000000"),
                            Name = "Spaghettis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0005-0000-000000000000"),
                            Name = "Guanciale"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0006-0000-000000000000"),
                            Name = "Pecorino romano"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0007-0000-000000000000"),
                            Name = "Tomatoes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0008-0000-000000000000"),
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0009-0000-000000000000"),
                            Name = "Pasta"
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.IngredientRecipe", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientRecipe");

                    b.HasData(
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0001-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0002-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0003-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0007-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0001-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0004-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0005-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0006-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0002-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0002-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0003-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0007-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0003-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0004-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0002-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0007-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0008-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0004-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0007-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0008-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0005-000000000000")
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0009-0000-000000000000"),
                            RecipeId = new Guid("00000000-0000-0000-0005-000000000000")
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.PreparationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("PreparationStep");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17894226-3453-4f7b-8595-7a1f8a4705b9"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000"),
                            Step = "Cook the eggs",
                            Title = "Cook eggs"
                        },
                        new
                        {
                            Id = new Guid("b68a6568-638e-4c94-bf1f-3ba5c8bada37"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000"),
                            Step = "Cook the bacon",
                            Title = "Cook bacon"
                        },
                        new
                        {
                            Id = new Guid("ee56ba65-d6d2-4cd6-8ea2-440279e96aef"),
                            RecipeId = new Guid("00000000-0000-0000-0001-000000000000"),
                            Step = "Fry the bread",
                            Title = "Fry bread"
                        },
                        new
                        {
                            Id = new Guid("24115123-84ac-4fe2-8ad6-445f00dc5c18"),
                            RecipeId = new Guid("00000000-0000-0000-0002-000000000000"),
                            Step = "Cook the guanciale",
                            Title = "Cook guanciale"
                        },
                        new
                        {
                            Id = new Guid("97372c90-7480-42aa-93b0-e129e85870a6"),
                            RecipeId = new Guid("00000000-0000-0000-0002-000000000000"),
                            Step = "Cook the spaghetti",
                            Title = "Cook spaghetti"
                        },
                        new
                        {
                            Id = new Guid("4168f5ba-6759-4e42-b8b6-f9faa3216573"),
                            RecipeId = new Guid("00000000-0000-0000-0003-000000000000"),
                            Step = "Fry the bacon",
                            Title = "Fry bacon"
                        },
                        new
                        {
                            Id = new Guid("74bcfb3d-f016-4317-909e-6300cc8da44d"),
                            RecipeId = new Guid("00000000-0000-0000-0003-000000000000"),
                            Step = "Cook the eggs",
                            Title = "Cook eggs"
                        },
                        new
                        {
                            Id = new Guid("7c034664-9ed3-44c3-a3c6-4de1824bf6d9"),
                            RecipeId = new Guid("00000000-0000-0000-0004-000000000000"),
                            Step = "Cook the beef and the bacon",
                            Title = "Cook beef and bacon"
                        },
                        new
                        {
                            Id = new Guid("7484bd7b-2ea1-47d4-aa2f-f64cffcc752e"),
                            RecipeId = new Guid("00000000-0000-0000-0004-000000000000"),
                            Step = "Cook the spaghetti",
                            Title = "Cook spaghetti"
                        },
                        new
                        {
                            Id = new Guid("bfd9fef8-ca01-4211-abb5-ed51bc771420"),
                            RecipeId = new Guid("00000000-0000-0000-0005-000000000000"),
                            Step = "Prepare the bolognese",
                            Title = "Prepare bolognese"
                        },
                        new
                        {
                            Id = new Guid("8fe5eff8-5206-43ba-938c-9c6778e93f5a"),
                            RecipeId = new Guid("00000000-0000-0000-0005-000000000000"),
                            Step = "Prepare the bechamel",
                            Title = "Prepare bechamel"
                        },
                        new
                        {
                            Id = new Guid("82682061-4d5d-4a81-af3d-4ad692b3692b"),
                            RecipeId = new Guid("00000000-0000-0000-0005-000000000000"),
                            Step = "Prepare the lasagna and place it in the oven.",
                            Title = "Prepare lasagna"
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecipeCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCategoryId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000000"),
                            CreatedOn = new DateTime(2023, 2, 26, 15, 28, 31, 203, DateTimeKind.Utc).AddTicks(9466),
                            Description = "Sometimes also called a 'fry-up', the full English breakfast consists of fried eggs, sausages, back bacon, tomatoes, mushrooms, fried bread and often a slice of white or black pudding (similar to bloodwurst). It is accompanied by tea or coffee and hot, buttered toast.",
                            RecipeCategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Title = "English breakfast"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000000"),
                            CreatedOn = new DateTime(2023, 2, 26, 15, 28, 31, 203, DateTimeKind.Utc).AddTicks(9469),
                            Description = "Spaghetti alla carbonara is an Italian pasta dish made with eggs, pecorino romano, guanciale and black pepper.",
                            RecipeCategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Title = "Spaghetti carbonara"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000000"),
                            CreatedOn = new DateTime(2023, 2, 26, 15, 28, 31, 203, DateTimeKind.Utc).AddTicks(9472),
                            Description = "A club sandwich, also called a clubhouse sandwich, is a sandwich consisting of bread (traditionally toasted), sliced cooked poultry, fried bacon, lettuce, tomato, and mayonnaise. It is often cut into quarters or halves and held together by cocktail sticks.",
                            RecipeCategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Title = "Club sandwich"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000000"),
                            CreatedOn = new DateTime(2023, 2, 26, 15, 28, 31, 203, DateTimeKind.Utc).AddTicks(9475),
                            Description = "Spaghetti bolognese consists of spaghetti (long strings of pasta) with an Italian ragù (meat sauce) made with minced beef, bacon and tomatoes, served with Parmesan cheese. Spaghetti bolognese is one of the most popular pasta dishes eaten outside of Italy.",
                            RecipeCategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Title = "Spaghetti bolognese"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000000"),
                            CreatedOn = new DateTime(2023, 2, 26, 15, 28, 31, 203, DateTimeKind.Utc).AddTicks(9478),
                            Description = "Lasagna Bolognese includes only fresh egg pasta, Bolognese ragù (slow-cooked meat sauce), creamy béchamel (white sauce) and plenty of grated Parmigiano cheese. The result is a melt in your mouth, creamy, decadent, and satisfying lasagna that is distinct to Italy.",
                            RecipeCategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Title = "Lasagna bolognese"
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.RecipeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Breakfast is the first meal of the day usually eaten in the morning. The word in English refers to breaking the fasting period of the previous night.",
                            Title = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Lunch is a meal eaten around the middle of the day. It is commonly the second meal of the day, after breakfast, and varies in size by culture and region.",
                            Title = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Dinner usually refers to what is in many Western cultures the largest and most formal meal of the day.Historically, the largest meal used to be eaten around midday, and called dinner.",
                            Title = "Dinner"
                        });
                });

            modelBuilder.Entity("Kitchen.Entities.IngredientRecipe", b =>
                {
                    b.HasOne("Kitchen.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientRecipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kitchen.Entities.Recipe", "Recipe")
                        .WithMany("IngredientRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Kitchen.Entities.PreparationStep", b =>
                {
                    b.HasOne("Kitchen.Entities.Recipe", "Recipe")
                        .WithMany("PreparationSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Kitchen.Entities.Recipe", b =>
                {
                    b.HasOne("Kitchen.Entities.RecipeCategory", "RecipeCategory")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeCategory");
                });

            modelBuilder.Entity("Kitchen.Entities.Ingredient", b =>
                {
                    b.Navigation("IngredientRecipes");
                });

            modelBuilder.Entity("Kitchen.Entities.Recipe", b =>
                {
                    b.Navigation("IngredientRecipes");

                    b.Navigation("PreparationSteps");
                });

            modelBuilder.Entity("Kitchen.Entities.RecipeCategory", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
